version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: Transfert-Telelec
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Telelec-PHP
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network


  db:
    image: mysql:8.0
    container_name: Telelec-MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: telelec
      MYSQL_USER: telelecuser
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"  # uniquement si tu veux accéder à la DB depuis l'extérieur (facultatif)

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
